import { 
  faPlusCircle,
  faAddressCard,
  faAddressBook,
  faTimes,
  faUserCircle,
  faUserPlus,
  faUndo,
  faSpinner,
  faSignOutAlt,
  faCalculator,
  faFileInvoice,
  faTrash,
  faSave,
  faFilePdf,
  faEdit,
  faPlus,
  faReply,
  faFileExcel,
  faInfoCircle,
  faDownload,
  faBuilding,
  faCheck,
  faExclamationTriangle
} from '@fortawesome/free-solid-svg-icons';

const icons: any = [ 
  faPlusCircle,
  faAddressCard,
  faAddressBook,
  faTimes,
  faUserCircle,
  faUserPlus,
  faUndo,
  faSpinner,
  faSignOutAlt,
  faCalculator,
  faFileInvoice,
  faTrash,
  faSave,
  faFilePdf,
  faEdit,
  faPlus,
  faReply,
  faFileExcel,
  faInfoCircle,
  faDownload,
  faBuilding,
  faCheck,
  faExclamationTriangle
];

export default icons;